# Generated by Django 5.2.7 on 2025-11-29 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_category_post_author_alter_comment_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
